packages:
  - crates/config
  - crates/conn-error
  - crates/devproxy
  - crates/hysteria
  - crates/profile

allowBuilds: {}

blockExoticSubdeps: true

catalog:
  "@taplo/cli": 0.7.0
  "@types/node": 25.9.1
  fd-lock: 2.1.1
  husky: 9.1.7
  markdownlint-cli2: 0.22.1
  oxfmt: 0.51.0
  oxlint: 1.66.0
  selfsigned: 5.5.0
  typescript: 6.0.3

minimumReleaseAge: 1440

storeDir: .cache/pnpm

minimumReleaseAgeExclude: []

overrides: {}

strictDepBuilds: true
